### ISSUE TITLE
HIP58 distance problem invalid beacons/witness

### ISSUE THREAD

**Issue by gandra01** [helium/HIP#410] opened 2022-05-20 11:12 UTC
Hello i would like to make proposal for adjustment of hip58.

I am getting too many invalids witnesses on mine beacon and i am getting invalid witnesses from others due limit 100km which is totaly fine by me.
But im failing to earn anything because of that.
I have plenty hs under 100km who can witness mine beacon and yet im getting invalid 7/14 very often due witness is too far which greatly impact mine reward.

Mine proposal is when hs send beacon dont let other hotspots who are above 100km to participate in lottery for witness. Like if limit is alredy here which is ok by me why at first place those hs above 100km even participate in poc since they are invalid by system. Its damaging valid beaconers and witnesses under 100km

**Comment by ilovespectra** [comment] 2022-05-20 15:42
Folks have lobbied this concern already, but it's been determined there's no useful sensor application capable of communication over 100km, let alone any that require it. HIP58 is designed to both prevent spoofing and encourage unique hotspot placement. the witnesses over 100km will need to be invalid for this fix to work, despite the fact spoofers will simply reassert their location to be within these limitations. I've been slowly aiming my mountain off-grid's directional antenna more and more downward every time I make a trip up there and am still witnessing and beaconing over 130km. There _can_ be _too good_ of a deployment now, but the network was designed to provide coverage to sensors incapable of communicating those distances so there's no benefit to the network to reward hotspots for providing unusable coverage. Focus your energy on maximizing the coverage you're providing to hotspots _nearby_, even if that means relocating to be closer to a town, or lower on the mast/mountain. My off-grids experience about a 25% invalid rate because of too great a distance, so my solution will simply be to reduce my range, and reducing elevation is the easiest way to do so.

**Comment by gandra01** [comment] 2022-05-20 16:03
Its not about limit. Its about to remove all hotspots from getting witness if they are 100km plus away. There is too many invalid witnesses in beacon

**Comment by jerryfudd** [comment] 2022-05-20 16:12
I asked this on Discord just the other day, if - for example 20 miners witness your beacon the 100km+ responders should be removed from the running before the max of 14 are selected as witnesses

**Comment by ilovespectra** [comment] 2022-05-20 16:30
i hear what you both are suggesting but that would negate the result of HIP58. Unfortunately solutions that are rewards-centric around proof-of-coverage will not impact the course of anti-gaming legislation on a network designed to transfer data.

**Comment by gandra01** [comment] 2022-05-20 17:30
It would not negate. Limit would stay as it is 100km. I just want beacons to go on hotspots under 100km. On that way rewards would go to valid witnesses only...

**Comment by ilovespectra** [comment] 2022-05-20 18:21
i suppose how i meant to phrase it is that the fact you and other hotspot owners wish you were getting more rewards for meaningless/useless/impossible coverage will not impact anti gaming policies created to prevent hotspots from being rewarded for providing meaningless/useless/impossible coverage. lower your antenna or aim it downward. 

there’s no benefit to the network hotspots proving coverage over 100km because there’s no proof sensors can communicate any more than 50km. there is already a large leniency built into HIP58, it will not stop gamers. literally nothing ever will. we can only continue to make things harder and less rewarding for them. the impact on the earnings of honest well placed hotspots will be a negligible. 

All of this has been iterated by core developers from Helium in previous iterations of these grievances, there will be no extension to 100km limit and no removal of >100km witnesses in the foreseeable future. off gridders and long distance crushers need now only adapt.

**Comment by gandra01** [comment] 2022-05-20 18:54
Pls go read what i writed. Either you are dumb or joking with me.

**Comment by gandra01** [comment] 2022-05-20 18:55
I do not want rewards from those 100km plus hotspots. I just want them to be removed from reward pool for beacons which will make invalids.

**Comment by jerryfudd** [comment] 2022-05-20 19:02
Likewise. So, for example if 20 respond to a beacon and 2 are over 100km then they get automatically stripped away and it's from the remaining 18 that the 14 witnesses get chosen.

I also am absolutely fine not getting rewarded for witnesses over 100km.

**Comment by gandra01** [comment] 2022-05-20 19:27
Idk i got feeling that they writed hip58 too fast to just patch it. By mine opinion it is not done propertly. Those from 100km should not be able to get in those 14 witneses.

I know thats why i edited msg. Gor pissed because ppl dont understand rly what is issue... I get it most of ppl dont even have witness above 30km. If i downgrade antenna or move it lower i wont have trouble with 100km plus hotspots but i will loose those under 100km because im surrounded by 2 sides with high mountians.

**Comment by jamiew** [comment] 2022-05-23 16:32
Thanks for your submission, but this repository is for Helium Improvement Proposals (HIPs) and is not a support or discussion forum. 

If you'd like to write and submit proposal, you should follow the format and process prescribed in HIP7, [Process for managing Helium Improvement Proposals](https://github.com/helium/HIP/blob/master/0007-managing-hip-process.md)

I've also written a rough guide to doing this using the github.com web interface: https://jamiedubs.com/blog/how-to-submit-helium-manufacturer-application/

I am closing this as `invalid` but feel free to ask further questions here or in Discord

**Closed by jamiew** 2022-05-23 16:32 UTC
